version: "3.8"
services:
# Database
  mongo:
    image: mongo
    # restart: always
    ports:
      - 27017:27017
    volumes: 
      - db_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
#     networks:
#       - backend

# # Backend
#   backend:
#     image: node_backend
#     ports:
#       - 3001:3001
#     networks: 
#       - backend
#       - frontend

# # Frontend
#   frontend:
#     image: node_frontend
#     ports:
#       - 3000:3000
#     networks: 
#       - frontend
      
# networks: 
#   backend:
#     driver: bridge
#   frontend:
#     driver: bridge

volumes:
  db_data: